language: python
python:
  - "2.7"
# command to install dependencies
install:
  - "pip install cython"
  - "dpkg -l"
  - "sh ./install-deps.sh"
  - "python setup.py build"
  - "python setup.py install"
# command to run tests
script: "cd Tests && make testpython"
