language: python
python:
  - "2.7"
# command to install dependencies
install:
  - "dpkg -l"
  - "pwd"
  - "cat /etc/debian_version"
  - "ps aux"
  - "ls"
  - "sh ./install-deps.sh"
  - "pip install cython"
  - "python setup.py build"
  - "python setup.py install"
# command to run tests
script: "cd Tests && make testpython"
