language: python
python:
  - "2.7"
# command to install dependencies
install:
  - "dpkg -l"
  - "pwd"
  - "cat /etc/debian_version"
  - "ps aux"
  - "ls"
  - "pip install cython"
  - "make"
# command to run tests
script: "cd Tests && make testpython"
